# Generated by Django 3.2.5 on 2021-11-01 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('place', models.CharField(max_length=50)),
                ('stipend', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=5)),
                ('eligibility', models.CharField(max_length=600)),
                ('prereq', models.CharField(max_length=400)),
                ('deliverables', models.CharField(max_length=400)),
                ('duration', models.CharField(max_length=50)),
                ('wishlist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('rollno', models.CharField(blank=True, max_length=100)),
                ('phoneno', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
