# Generated by Django 2.2.5 on 2021-11-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211102_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='yos',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
