# Generated by Django 3.2.9 on 2022-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20211103_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonathon_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alum_id', models.CharField(blank=True, max_length=10)),
                ('alum_name', models.CharField(blank=True, max_length=255)),
                ('phone1', models.CharField(blank=True, max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('phone3', models.CharField(blank=True, max_length=20)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('stud_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
