# Generated by Django 3.2.9 on 2022-07-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_phonathon_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonathon_data',
            name='ldap',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
