# Generated by Django 4.1.2 on 2022-10-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_phonathon_data_ldap"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="eligible",
            field=models.BooleanField(default=False),
        ),
    ]
